services:
  bot:
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
    image: jvnus/anvil:latest
    env_file:
      - ./apps/bot/.env
  dashboard:
    platform: linux/arm64
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    image: jvnus/anvil_dashboard:latest
    ports:
      - "4000:4000"
      - "9000:9000"
    env_file:
      - ./apps/dashboard/.env
  docs:
    platform: linux/arm64
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    image: jvnus/anvil_docs:latest
    ports:
      - "4001:4001"
    env_file:
      - ./apps/docs/.env
